name:    hello
version: 0.1.0.0
license: BSD3

dependencies:
  - base
  - async
  - base-unicode-symbols
  - binary
  - bytestring
  - case-insensitive
  - classy-prelude
  - conduit
  - containers
  - cryptohash-sha256
  - cryptohash-sha512
  - data-default
  - data-fix
  - directory
  - ed25519
  - entropy
  - exceptions
  - extra
  - filepath
  - fixed-vector
  - flat
  - ghc-prim
  - Glob
  - hashable
  - hashtables
  - http-client
  - http-client-tls
  - http-types
  - integer-gmp
  - iproute
  - largeword
  - lens
  - lmdb
  - lock-file
  - megaparsec
  - memory
  - mtl
  - multimap
  - murmur3
  - network
  - optparse-applicative
  - para
  - pretty-show
  - primitive
  - process
  - QuickCheck
  - random
  - regex-tdfa
  - regex-tdfa-text
  - resourcet
  - rio
  - sdl2
  - sdl2-image
  - semigroups
  - smallcheck
  - stm
  - stm-chans
  - tasty
  - tasty-golden
  - tasty-hunit
  - tasty-quickcheck
  - tasty-th
  - template-haskell
  - terminal-progress-bar
  - terminal-size
  - terminfo
  - text
  - these
  - time
  - transformers
  - unix
  - unliftio
  - unliftio-core
  - unordered-containers
  - urbit-hob
  - utf8-string
  - vector
  - wai
  - wai-conduit
  - warp
  - warp-tls
  - web3
  - websockets

library:
  source-dirs: src

executables:
  hello-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hello

tests:
  hello-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hello

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - EmptyDataDecls
  - EmptyDataDeriving
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - PatternSynonyms
  - QuasiQuotes
  - Rank2Types
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UnboxedTuples
  - UnicodeSyntax
  - ViewPatterns
