name: vere
version: 0.1.0
license: AGPL-3.0-only

default-extensions:
 - DeriveGeneric
 - FlexibleContexts
 - LambdaCase
 - NoImplicitPrelude
 - OverloadedStrings
 - QuasiQuotes
 - ScopedTypeVariables
 - TemplateHaskell
 - TypeApplications
 - UnicodeSyntax
 - ViewPatterns

dependencies:
 - base
 - classy-prelude
 - stm
 - stm-chans
 - async
 - lens
 - largeword
 - time

executables:
  vere:
    main: Main.hs
    source-dirs: .
    ghc-options:
      - -threaded
