language: c
script: make DEBUG=yes SANITIZE=$ASAN && make test # no ./configure

# Uncomment me if this gets annoying
#
# notifications:
#   email: false

matrix: include
  - os: linux
    env:
      - ASAN=no
      - FILENAME=urbit-linux
    addons:
      apt:
        packages:
        - libgmp3-dev
        - libsigsegv-dev
        - openssl
        - libssl-dev
        - libncurses5-dev
        - make
        - exuberant-ctags
        - automake
        - autoconf
        - libtool
        - g++
        - ragel
        - cmake
        - re2c
        - libcurl4-gnutls-dev
        - python
  - os: osx
    before_install:
      - brew install --only-dependencies urbit
    env:
      - ASAN=yes
      - FILENAME=urbit-osx

# before_deploy: "make deb" # TODO
deploy:
  skip_cleanup: true
  provider: releases
  prerelease: true # turn this off for official releases
  api_key:
    secure: zEmeceUBtdtI3TsSUZ6zA6341jH6CGmjHinTc9EFQhqOvtd9niIeVcwURd9E2HsZ0UlzzZT4yAoYrUGvw50p/eAgTiD0FUMyIQSw8/kP1CoqKmY8AG60DPHL8U9D4bnWrdMuTiapVhdQV5KY4cUh0XIkDAW/iQTqfSmTQvI8KBimMMry1xdJyJ3p9kZKv/h21ybdAxOrRijBIk6QY8ZGo6w59OioflmfepfYvELTrYoE1fe/41SepIv7fWCw2nQMPpulgAxkg2pTC7cqqmhcJ1NNn94rwqV7T6T5OiK3amZv1N2OuDLOnchHlHK7aFAHsf4hQ61Is3kBUHQrAPflF8XHualldqOjoWt5wH7sCkKCQduf/2igBmJRFcQI469oBJhLAwf3IS+h7DF+3KOuocTYQnbwdx1spgVpyl2WUnq/wFigCrIH6O5XsvwGdI1VyfhalwDYqA4lL7nOAk7F0XQj6tcCR6YgHkDff9ZTCKOT5ZqYhQ4MeibzeQXmhAlwso4gjt9CJ8+TNz3FG7UgNrS/zdzfe57pIhg1Otfp0EvA76XQN3UvK6ZTQNLDVXRzviZUfB2osXao8/aqZoqSml/vDR4syp/Pg23JRXZQWnh+ZVqQ/sgqIv5Eg0+BJ1oyvwLKLrZ2XpmhYs3qKKodmMxmWM7AKa1zL6nadr5jkF8=
  file: bin/urbit # TODO upload package from before_deploy
  name: $FILENAME
  on:
    repo: joemfb/urbit
    tags: true
