name: urbit-uruk-rts
version: 0.1.0
license: MIT
license-file: LICENSE

library:
  source-dirs: lib
  ghc-options:
    - -static
    - -O2
    - -fwarn-incomplete-patterns

executables:
  supermoon:
    main: Main.hs
    source-dirs: app/supermoon
    dependencies:
      - urbit-uruk
      - urbit-uruk-rts
    ghc-options:
      - -threaded
      - -rtsopts
      - -static
      - -O2
      - "-with-rtsopts=-N"
      - -fwarn-incomplete-patterns

  arvomoon:
    main: Main.hs
    source-dirs: app/arvomoon
    dependencies:
      - haskeline
      - urbit-uruk
      - urbit-uruk-rts
    ghc-options:
      - -threaded
      - -rtsopts
      - -static
      - -O2
      - "-with-rtsopts=-N"
      - -fwarn-incomplete-patterns

dependencies:
  - base
  - bound
  - bytestring
  - classy-prelude
  - cryptohash-sha256
  - containers
  - deriving-compat
  - directory
  - file-embed
  - flat
  - filepath
  - ghc-prim
  - hashable
  - hexstring
  - lens
  - megaparsec
  - mtl
  - multimap
  - para
  - positive
  - pretty-show
  - primitive
  - raw-strings-qq
  - serialise
  - store
  - template-haskell
  - text
  - time
  - transformers
  - transformers-compat
  - unordered-containers
  - urbit-atom
  - urbit-noun
  - urbit-uruk

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - PatternSynonyms
  - QuasiQuotes
  - Rank2Types
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UnboxedTuples
  - UnicodeSyntax
  - ViewPatterns
