name: urbit-atom
version: 0.10.1
license: MIT
license-file: LICENSE

library:
  source-dirs: lib
  ghc-options:
    - -fwarn-incomplete-patterns
    - -fwarn-unused-binds
    - -fwarn-unused-imports
    - -Werror
    - -O2

executables:
  urbit-atom:
    source-dirs: app
    main: Main.hs
    dependencies:
      - urbit-atom
    ghc-options:
      - -threaded
      - -rtsopts
      - -static
      - -O2
      - "-with-rtsopts=-N"

dependencies:
  - base == 4.12.0.0
  - bytestring == 0.10.8.2
  - ghc-prim == 0.5.3
  - integer-gmp == 1.0.2.0
  - primitive == 0.6.4.0
  - text == 1.2.3.1
  - vector == 0.12.0.3

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - PatternSynonyms
  - QuasiQuotes
  - Rank2Types
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UnboxedTuples
  - UnicodeSyntax
  - ViewPatterns
