name: urbit-atom
version: 0.10.1
license: MIT
license-file: LICENSE

ghc-options:
  # -fwarn-incomplete-patterns
  # -fwarn-unused-binds
  # -fwarn-unused-imports
  - -Werror
  - -O2

library:
  source-dirs: lib
  dependencies:
    - base == 4.12.0.0
    - bytestring == 0.10.8.2
    - ghc-prim == 0.5.3
    - integer-gmp == 1.0.2.0
    - primitive == 0.6.4.0
    - text == 1.2.3.1
    - vector == 0.12.0.3

tests:
  urbit-atom-tests:
    source-dirs: test
    main: Main.hs
    ghc-options: "-threaded -rtsopts -with-rtsopts=-N"
    dependencies:
      - base
      - bytestring
      - QuickCheck
      - text
      - urbit-atom
      - vector

executables:
  urbit-atom:
    source-dirs: app
    main: Main.hs
    ghc-options: "-threaded -rtsopts -with-rtsopts=-N"
    dependencies:
      - base
      - urbit-atom

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - PatternSynonyms
  - QuasiQuotes
  - Rank2Types
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UnboxedTuples
  - UnicodeSyntax
  - ViewPatterns
